# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Chat App CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: |
          Backend/package-lock.json
          Frontend/package-lock.json

    # ================= BACKEND =================
    - name: Install backend dependencies
      working-directory: ./Backend
      run: npm ci

    - name: Create backend .env file
      working-directory: ./Backend
      run: |
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
        echo "MONGO_URL=${{ secrets.MONGO_URL }}" >> .env
        echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> .env
        echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" >> .env
        echo "PORT=${{ secrets.PORT }}" >> .env
        echo "CLIENT_URL=${{ secrets.CLIENT_URL }}" >> .env

    - name: Run backend tests
      working-directory: ./Backend
      run: npm test --if-present
      
   # ================= FRONTEND =================
    - name: Install frontend dependencies
      working-directory: ./Frontend
      run: npm ci
      
    - name: Create frontend .env file
      working-directory: ./Frontend
      run: |
        echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env
        echo "VITE_SOCKET_URL=${{ secrets.VITE_SOCKET_URL }}" >> .env   

    - name: Build frontend
      working-directory: ./Frontend
      run: npm run build --if-present
